### ISSUE TITLE
Where is the data getting stored?

### ISSUE THREAD

**Issue by vishal-mourya** [e-Luminous/src#32]
Hey can you let me know that where is the data actually getting stored, of login/signup page. because I do not have sqllite and sql server on my PC still the project is running perfectly fine.

Hoping to hear from you soon.

Thanks & Regards
Vishal Mourya

**Comment by shunjid** [comment]
Hey @vishal-mourya

Thank you for your query. 

We have used SQLite as a database here for quick demonstration purposes. SQLite doesn't require any server to be installed to get started. When you build or restore the project, ASP.NET Core Runtime installs the required NuGet package inside the project directory in your system.

If you want to migrate the project to another database, then you just need to change the source of your ConnectionString in the appsettings.json file and change the database service in the Startup.cs file.
